# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestentriesplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_blog_latestentriesplugin', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
